# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_mail.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import pandas as pd
from threading import Thread
from html_body import body


def dialog_msg(msg):
    mbox = QtWidgets.QMessageBox()
    mbox.setWindowTitle("메일머지")
    mbox.setText(msg)
    mbox.setStandardButtons(QtWidgets.QMessageBox.Ok)
    mbox.exec_()


class MAIL_THREAD(Thread):
    def __init__(self, df, title, id, pw, html, btn, log):
        super().__init__()
        self.df, self.title, self.id, self.pw, self.html = df, title, id, pw, html
        self.btn, self.log = btn, log

    def run(self):
        for idx, row in self.df.iterrows():
            try:
                creator, email, created = (
                    row["CREATOR"],
                    row["CREATOR EMAIL"],
                    row["CREATED"],
                )
                rate, tour, contents = (row["RATE"], row["TOUR"], row["CONTENT"])
            except:
                dialog_msg("[오류] 엑셀 파일을 체크하십시오.")
                self.btn.setDisabled(False)
                return
            try:
                msg = MIMEMultipart("alternative")
                msg["Subject"] = self.title
                msg["From"] = self.id
                msg["To"] = email

                body = self.html.replace("$%tour%$", str(tour))
                body = body.replace("$%rate%$", str(rate))
                body = body.replace("$%CREATOR%$", str(creator))
                body = body.replace("$%CREATED%$", str(created))
                body = body.replace("$%CONTENT%$", str(contents))
                part = MIMEText(body, "html")
                msg.attach(part)
                mail = smtplib.SMTP("smtp.gmail.com", 587)
                mail.ehlo()
                mail.starttls()
            except:
                dialog_msg("[오류] 이메일 전송 중 문제가 발생했습니다.")
                self.btn.setDisabled(False)
                return
            try:
                mail.login(self.id, self.pw)
            except:
                dialog_msg("[오류] 회원정보가 일치하지 않습니다.")
                self.btn.setDisabled(False)
                return
            try:
                mail.sendmail(self.id, email, msg.as_string())
                mail.quit()
                self.log.addItem("[%d] %s 전송 성공 완료" % ((idx + 1), email))
            except:
                dialog_msg("[오류] 올바르지 않은 HTML 양식입니다.")
                self.btn.setDisabled(False)
                return

        dialog_msg("[완료] 메일 %d명 송부 완료했습니다." % (idx + 1))
        self.btn.setDisabled(False)


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(591, 711)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.label_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout.addWidget(self.label_title)
        spacerItem1 = QtWidgets.QSpacerItem(
            10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.lineEdit_mail_title = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_mail_title.setObjectName("lineEdit_mail_title")
        self.horizontalLayout.addWidget(self.lineEdit_mail_title)
        spacerItem2 = QtWidgets.QSpacerItem(
            30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.comment = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.comment.setObjectName("comment")
        self.verticalLayout.addWidget(self.comment)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 470, 571, 71))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_mail_id = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_mail_id.setObjectName("label_mail_id")
        self.horizontalLayout_2.addWidget(self.label_mail_id)
        self.lineEdit_id = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.horizontalLayout_2.addWidget(self.lineEdit_id)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_mail_pw = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_mail_pw.setObjectName("label_mail_pw")
        self.horizontalLayout_3.addWidget(self.label_mail_pw)
        self.lineEdit_pw = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_pw.setObjectName("lineEdit_pw")
        self.horizontalLayout_3.addWidget(self.lineEdit_pw)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(
            100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem3)
        self.pushButton_sendmail = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_sendmail.setEnabled(True)
        self.pushButton_sendmail.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_sendmail.setIconSize(QtCore.QSize(15, 16))
        self.pushButton_sendmail.setObjectName("pushButton_sendmail")
        self.pushButton_sendmail.clicked.connect(self.send_mail)
        self.horizontalLayout_4.addWidget(self.pushButton_sendmail)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem4)
        self.listView_log = QtWidgets.QListWidget(Form)
        self.listView_log.setGeometry(QtCore.QRect(10, 550, 571, 151))
        self.listView_log.setObjectName("listView_log")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "메일 머지"))
        self.label_title.setText(_translate("Form", " 제목"))
        self.comment.setText(_translate("Form", " mailmerge.xlsx 이름은 변경하시면 안됩니다."))
        self.label_mail_id.setText(_translate("Form", "  아이디  "))
        self.label_mail_pw.setText(_translate("Form", " 비밀번호"))
        self.pushButton_sendmail.setText(_translate("Form", "   메일 보내기  "))
        self.textEdit.setPlainText(body)

    def send_mail(self):
        self.pushButton_sendmail.setDisabled(True)

        html = self.textEdit.toPlainText()
        title = self.lineEdit_mail_title.text()
        id = self.lineEdit_id.text()
        pw = self.lineEdit_pw.text()
        if title == "":
            dialog_msg("[오류] 제목을 입력하세요.")
            self.pushButton_sendmail.setDisabled(False)
            return
        try:
            df = pd.read_excel("./mailmerge.xlsx", engine="openpyxl")
        except:
            dialog_msg("[오류] mailmerge.xlsx 파일을 찾을 수 없습니다.")
            self.pushButton_sendmail.setDisabled(False)
            return
        thread = MAIL_THREAD(
            df=df,
            title=title,
            id=id,
            pw=pw,
            html=html,
            btn=self.pushButton_sendmail,
            log=self.listView_log,
        )
        thread.setDaemon(True)
        thread.start()


if __name__ == "__main__":
    # "younjung1996@gmail.com", "tptyykkdhlwsozmh"
    import sys

    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
